### ISSUE TITLE
I think you can include Form properties here

### ISSUE THREAD

**Issue by ianjaspersantos** [pedromassango/build_context#2]
Hi Pedro, you can also add form contexts here. Thanks :)
I was also thinking of this kind of package. Haha

Also you can try Navigator.of(context)

**Comment by pedromassango** [comment]
Thanks @ianjaspersantos 

What do you mean by add form contexts?

I already added support for `Navigator.of(context)` things. But it might change from `context.push(...)` to `context.navigator.push(...)`

**Comment by ianjaspersantos** [comment]
There are also methods like
Form.of(context).validate();
Form.of(context).save();

Which you also can add on extension :)

**Comment by pedromassango** [comment]
I get it. Thanks. It should be available on version `0.0.4`

**Comment by pedromassango** [comment]
Fixed on https://github.com/pedromassango/build_context/commit/81bb084c429c68f9675c1201ff4bdb238a75becb
