### ISSUE TITLE
context.focusScope.requestFocus() NOT FOUND

### ISSUE THREAD

**Issue by matheusperez** [pedromassango/build_context#5]
![image](https://user-images.githubusercontent.com/19479787/80163863-d48bf580-85ad-11ea-87dd-f4e0c4b81494.png)

Version package: ^1.1.0
Version dart: Channel stable, v1.12.13+hotfix.9

**Comment by pedromassango** [comment]
Thanks for opening this issue. It looks like you don't have a context instance in your class. Please make sure your `context` property if of type `BuildContext`.


Let me know if you've solve  it.

**Comment by matheusperez** [comment]
One got it, I thought it could be used in any class, thank you very much for the answer
