### ISSUE TITLE
Errors in Flutter  v1.18.0-7.0.pre.19

### ISSUE THREAD

**Issue by vasilich6107** [pedromassango/build_context#6]
Hi. Thanks a lot for this package.
What is the maximum supported version of Flutter?

In v1.18.0-7.0.pre.19 I have 2 errors:
```
Compiler message:
../../.pub-cache/hosted/pub.dartlang.org/build_context-1.1.0/lib/src/build_context_impl.dart:44:38: Error: This expression has type 'void' and can't be used.
  bool pop<T>(T result) => Navigator.pop(this, result);
                                     ^
../../.pub-cache/hosted/pub.dartlang.org/build_context-1.1.0/lib/src/build_context_impl.dart:142:23: Error: No named parameter with the name 'focusPrevious'.
      _node().unfocus(focusPrevious: focusPrevious);
```

**Comment by EdsonOnildoJR** [comment]
This package works well only in stable channel of flutter. To works in another channels, you should make [this changes](https://github.com/pedromassango/build_context/compare/master...EdsonOnildoJR:master#diff-a7b17259dedc797b3ef1ea5e7ce6dbbc).

**Comment by vasilich6107** [comment]
Thank for your response!
I will close this issue for now. I copy/pasted the required functionality into my project.
May be lately I'll move to this package.
